---
locale: es
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Recorrer elementos
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Modificar una lista
  checked: false
name: Para que se utiliza-b?
