---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: for ([expresiónInicial]; [expresiónCondicional];[expresiónDeActualización]
    )
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: for ([expresiónDeActualización]; [expresiónCondicional];[expresiónInicial])
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: for ([expresiónCondicional]; [expresiónDeActualización];[expresiónInicial])
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: for ([expresiónInicial]; [expresiónDeActualización];[expresiónCondicional]
    )
  checked: false
name: Declaración for
